apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: xbuwnxeft-python
  janus-idp.io/tekton: xbuwnxeft-python
  backstage.io/kubernetes-id: xbuwnxeft-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: xbuwnxeft-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
